### PR TITLE
Add support for django 4.0

### PR DESCRIPTION
**Pull request by kernicPanel**
Django 4.0 introduces changes on middlewares, and signals. https://docs.djangoproject.com/en/4.0/releases/4.0/

> The get_response argument for django.utils.deprecation.MiddlewareMixin.__init__() is required and doesn’t accept None.

> The providing_args argument for django.dispatch.Signal is removed.

### CODE REVIEW

**Comment by leplatrem** [comment]
@kernicPanel Could you try to rebase your PR on latest master?

**Comment by kernicPanel** [comment]
@leplatrem I rebased this PR.

**Comment by leplatrem** [comment]
Thanks, apparently that wasn't enough to make the tests pass :(

**Comment by diox** [comment]
That's because you're trying to build Django 4.0 support on Python 3.6/3.7. Django 4.0 requires Python 3.8 or greater. In addition, there is also a failure for py38-lint:
`src/dockerflow/django/middleware.py:42:52: BLK100 Black would make changes.`

**Comment by kernicPanel** [comment]
Thanks for pointing this out, @diox 
As I'm not familiar with tox, I hope this would pass now.

**Review by diox — APPROVED** [review]
Looks good, thanks for taking this on, @kernicPanel !

**Comment by kernicPanel** [comment]
Thanks for your support @diox and @leplatrem , I'm glad to have contributed!

**Pull request merged**
