### PR TITLE
Add support for Sanic 20.3.0 and up

### PR DESCRIPTION
**Pull request by relud**
support for treating request as a dict was deprecated in favor of `request.ctx` in Sanic 19.9 (https://github.com/huge-success/sanic/pull/1666) and removed in 20.3 (https://github.com/huge-success/sanic/pull/1801)

### CODE REVIEW

**Comment by relud** [comment]
test failures are unrelated and fixed in #53

**Review by jezdez — APPROVED** [review]
LGTM!

**Comment by jezdez** [comment]
This is out as 2020.10.0 🎊

**Pull request merged**
